[tool.black]
line-length = 100
target-version = ["py311"]
[tool.isort]
profile = "black"
line_length = 100
[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","SIM","B"]
ignore = ["E501"]
[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
strict_optional = true
disallow_untyped_defs = true
